### ISSUE TITLE
product tabs (installation, changelog, faq...) do not appear on translated pages

### ISSUE THREAD

**Issue by GuduleLapointe** [magicoli/woocommerce-domain-names#3]
Noticed on websites with WPML translation
* only description tab appear on translated pages
* content of the other tabs do not appear on translation interface either
* all tabs should appear on translated pages, whether they are translated or not
* changelog could remain untranslated, localizing it would be an unnecessary additional task

**Comment by magicoli** [comment]
This issue is related to WooPUS wordpress plugin, not this project.
